<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>UrbanArtDropFinder.Api-622c0fa5-0bdf-4cf7-873f-bf56d800d0df</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Grpc.AspNetCore" Version="2.66.0" />
    <PackageReference Include="Grpc.Tools" Version="2.66.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UrbanArtDropFinder.Application\UrbanArtDropFinder.Application.csproj" />
    <ProjectReference Include="..\UrbanArtDropFinder.Infrastructure\UrbanArtDropFinder.Infrastructure.csproj" />
    <ProjectReference Include="..\UrbanArtDropFinder.Contracts\UrbanArtDropFinder.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\..\..\protos\urban_art_drop_finder.proto" GrpcServices="Server" />
  </ItemGroup>

</Project>
