// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrbanArtDropFinder.Persistence.Db;

#nullable disable

namespace UrbanArtDropFinder.Persistence.Migrations
{
    [DbContext(typeof(UrbanArtDbContext))]
    [Migration("20260316211325_AddArtPieceAssetFiles")]
    partial class AddArtPieceAssetFiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UrbanArtDropFinder.Domain.Art.ArtPiece", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetKind")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ArtPieces");
                });

            modelBuilder.Entity("UrbanArtDropFinder.Domain.Art.ArtPieceAssetFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtPieceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("BinaryData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ArtPieceId")
                        .IsUnique();

                    b.ToTable("ArtPieceAssetFiles");
                });

            modelBuilder.Entity("UrbanArtDropFinder.Domain.Art.ArtPiecePhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtPieceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("BinaryData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ArtPieceId");

                    b.ToTable("ArtPiecePhotos");
                });

            modelBuilder.Entity("UrbanArtDropFinder.Domain.Comments.DropComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnonymousNickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DropId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReported")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DropId");

                    b.ToTable("DropComments");
                });

            modelBuilder.Entity("UrbanArtDropFinder.Domain.Configuration.AppConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MainMapRadiusKm")
                        .HasColumnType("int");

                    b.Property<int>("MiniMapRadiusKm")
                        .HasColumnType("int");

                    b.Property<bool>("ShowExactPositionWhenFullyClaimed")
                        .HasColumnType("bit");

                    b.Property<string>("SmtpHost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnclaimedDropRadiusKm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AppConfigurations");
                });

            modelBuilder.Entity("UrbanArtDropFinder.Domain.Drops.Drop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtPieceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DropMakerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStationary")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int?>("PortableItemCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Drops");
                });

            modelBuilder.Entity("UrbanArtDropFinder.Domain.Drops.DropItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ClaimedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ClaimedByAnonymousNickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClaimedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DropId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsClaimed")
                        .HasColumnType("bit");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("DropId");

                    b.HasIndex("QrToken")
                        .IsUnique();

                    b.ToTable("DropItems");
                });

            modelBuilder.Entity("UrbanArtDropFinder.Domain.Drops.DropLocationPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("BinaryData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("DropId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DropId");

                    b.ToTable("DropLocationPhotos");
                });

            modelBuilder.Entity("UrbanArtDropFinder.Domain.Users.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProviderAccount")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("NextLoginAllowedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("UrbanArtDropFinder.Domain.Users.UserProviderLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderSubject")
                        .IsUnique();

                    b.ToTable("UserProviderLinks");
                });

            modelBuilder.Entity("UrbanArtDropFinder.Domain.Art.ArtPieceAssetFile", b =>
                {
                    b.HasOne("UrbanArtDropFinder.Domain.Art.ArtPiece", null)
                        .WithOne("AssetFile")
                        .HasForeignKey("UrbanArtDropFinder.Domain.Art.ArtPieceAssetFile", "ArtPieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UrbanArtDropFinder.Domain.Art.ArtPiecePhoto", b =>
                {
                    b.HasOne("UrbanArtDropFinder.Domain.Art.ArtPiece", null)
                        .WithMany("Photos")
                        .HasForeignKey("ArtPieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UrbanArtDropFinder.Domain.Drops.DropItem", b =>
                {
                    b.HasOne("UrbanArtDropFinder.Domain.Drops.Drop", null)
                        .WithMany("Items")
                        .HasForeignKey("DropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UrbanArtDropFinder.Domain.Drops.DropLocationPhoto", b =>
                {
                    b.HasOne("UrbanArtDropFinder.Domain.Drops.Drop", null)
                        .WithMany("LocationPhotos")
                        .HasForeignKey("DropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UrbanArtDropFinder.Domain.Art.ArtPiece", b =>
                {
                    b.Navigation("AssetFile");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("UrbanArtDropFinder.Domain.Drops.Drop", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("LocationPhotos");
                });
#pragma warning restore 612, 618
        }
    }
}
